name: https.jsCI

on:
  push:
    branches:
      - main
      # - src/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: https.js CI
      # To use latest action, specify "release-master" instead of "v0.0.3"
      uses: satackey/action-js-inline@v0.0.2
      id: getdata
      with:
        # Edit the following line to install packages required to run your script.
        # required-packages: https.js
        script: |
          console.log(process.execPath)
          console.log(__dirname)
          console.log(process.cwd())
